### ISSUE TITLE
Calling `patternToRegex` on `<all_urls>` should match `about:srcdoc`

### ISSUE THREAD

**Issue by twschiller** [fregante/webext-patterns#13]
## Report
- `<all_urls>` matches `srcdoc:` iframes
- You can check that by setting a context menu with `<all_urls>` as the pattern: https://developer.chrome.com/docs/extensions/reference/api/contextMenus#method-create
- Currently it only matches http(s), ftp, file: https://github.com/fregante/webext-patterns/commit/00ce6ad717997c71d12008d57a69f89f8f96d8bd#diff-dcdc3e0b3362edb8fec2a51d3fa51f8fb8af8f70247e06d9887fa934834c9122R30

## Related
- https://github.com/fregante/webext-patterns/issues/3

**Comment by fregante** [comment]
It's a bit complicated because `about:srcdoc` and `data:` URLs are not allowed in the manifest and Chrome doesn't inject the content scripts into them _if they're the top frame:_

https://stackoverflow.com/a/31052496

```
data:text/html,%3Ch1%3EHello%2C%20World%21%3C%2Fh1%3E
```
<img width="1190" alt="Screenshot" src="https://github.com/fregante/webext-patterns/assets/1402241/ea36445c-263a-4268-8c63-74f5c5e73594">

So there's a varying degree of support for these protocols, depending on where they're used. 

I might add support for it via option, but for the issue at hand, you can probably inline a specific check on this line for now until I figure out what to do:

https://github.com/pixiebrix/pixiebrix-extension/blob/d39b94c3dc52f8f29b6340e22b30101d10be1c7b/src/bricks/available.ts#L31

**Comment by fregante** [comment]
More context in the source:

https://chromium.googlesource.com/chromium/src/+/refs/heads/main/extensions/common/url_pattern.cc#31

No mentions of srcdoc found :(

**Comment by twschiller** [comment]
I agree that it would need to be behind and option/in a different method.

> I might add support for it via option, but for the issue at hand, you can probably inline a specific check on this line for now until I figure out what to do:

👍

**Comment by fregante** [comment]
As specified in https://github.com/pixiebrix/pixiebrix-extension/issues/8170, `about:srcdoc` is not something the browser actually matches patterns against.

From this API's standpoint:

- does `about:srcdoc` match `<all_urls>`? No

**Comment by fregante** [comment]
However:

- does `<all_urls>` inject into `about:srcdoc`? **Yes** if the parent is not chrome-extension://
- does `*://*/*` inject into `about:srcdoc`? **Yes** if the parent is not chrome-extension://
- does _anything else_ inject into `about:srcdoc`? **Maybe**, undeterminable

Ideally you should follow the browser and never match `about:srcdoc`:

```js
if (location.href === 'about:srcdoc') {
  return pattern.matches(window.parent.location.href); // Parent URL
} else {
  return pattern.matches(location.href);
}
```

You can take shortcuts to this depending on what you want to do next. Since `<all_urls>` and `*://*/*` are equivalent in this scenario, the function can be:

```js
function shouldBrickRunHere(pattern) {
  //     100% certainty                    probably 🤞                 probably 🤞 
  return pattern.matches(location.href) || pattern === `<all_urls>` || pattern ===  `*://*/*`;
}

**Comment by fregante** [comment]
From an extension architecture standpoint, I believe iframes should be dependents/puppets of the main frame and should not run anything independently, but this is much harder to achieve.
